#!/bin/bash
##---------------------------------------------------------------------------------------------------------------------------##
###############################################################################################################################
##---------------------------------------------------------------------------------------------------------------------------##
##
## Abstract:
##   Shell script bush: Run an interactive shell with the file creation mode mask reset to the default value.
## Such a shell is particularly convenient when building software to be installed into the system.
##
## Details:
##   None.
##
## References:
## - bash(1) man page
##   --> $ man bash
## - Advanced Bash-Scripting Guide
##   --> http://www.tldp.org/LDP/abs/abs-guide.pdf
##
## Author:
##   Michael H. Pock || MHP || mhp77@gmx.at
##
## © Copyleft 2016 MHP
##
##---------------------------------------------------------------------------------------------------------------------------##
###############################################################################################################################
##---------------------------------------------------------------------------------------------------------------------------##

. ~/.bash_common || exit

##---------------------------------------------------------------------------------------------------------------------------##

refdir=/

tmpdir=/tmp

##---------------------------------------------------------------------------------------------------------------------------##

function display_help_message {
  echo "${0}: usage: ${0##*/}" >&2
  exit ${stat_incorrect_usage}
}

##---------------------------------------------------------------------------------------------------------------------------##

[ ${#} -gt 0 ] && display_help_message

##---------------------------------------------------------------------------------------------------------------------------##

filename_to_dirname refdir

default_mask=$(ls -ld "${refdir}")
default_mask=${default_mask#*([[:blank:]])d}
default_mask=u\=${default_mask:0:3},g\=${default_mask:3:3},o\=${default_mask:6:3}
default_mask=${default_mask//[st]/x}
default_mask=${default_mask//[ST-]/}

##---------------------------------------------------------------------------------------------------------------------------##

trap 'rm -f "${rcfile}"' EXIT
rcfile=$(mktemp --tmpdir="${tmpdir}" bashrc.XXXXX)

[ -f ~/.bashrc ] && cat ~/.bashrc >"${rcfile}"

cat >>"${rcfile}" <<EOF
umask '${default_mask}'
EOF

cat >>"${rcfile}" <<'EOF'
PS1=${PS1/\\\$/[\$(umask -S)]\\\$}
rm "${BASH_SOURCE}"
EOF

##---------------------------------------------------------------------------------------------------------------------------##

## According to the Bash manual page, the --rcfile option prevents not only the personal initialization script ~/.bashrc, but
## also the system-wide initialization script /etc/bash.bashrc from being read and interpreted. At least for Bash 4.1.5, the
## latter is not the case, though. But we do not mind since this comes in rather handy here.
bash --rcfile "${rcfile}"

##---------------------------------------------------------------------------------------------------------------------------##


## LocalWords: rcfile bashrc
